### ISSUE TITLE
The repo is too large

### ISSUE THREAD

**Issue by KOLANICH** [LaurentRDC/scikit-ued#32]
57MiB is too large for such a git repo. Usualy this happens if someone stores binaries in the repo. Consider moving the binaries out of the repo (for example wheels) and [using `git lfs`](https://help.github.com/articles/configuring-git-large-file-storage/) for the ones which cannot be moved out. I insist on rewriting the history. https://github.com/bozaro/git-lfs-migrate and https://rtyley.github.io/bfg-repo-cleaner/ may be helpful. Removing binary dependencies in f7de365 won't help: the history still persists, the repo is still large.

**Comment by LaurentRDC** [comment]
Good catch, I had not noticed it became this big until I cloned it yesterday. It was foolish of me to include all those wheels, but it was before scikit-ued was available on conda-forge.

I'm going through the BFG website. Seems like a good tool. Once I have successfully rewritten the history, I will let you know.

**Comment by LaurentRDC** [comment]
@KOLANICH Thanks to your suggestions, I was able to remove all wheels from the git history. Cloning a fresh version of the repo confirms that the size (of the .git folder) has been reduced from 180MiB down to 20MiB.

**Comment by KOLANICH** [comment]
You still have binaries in the repo, for example https://github.com/LaurentRDC/scikit-ued/tree/master/docs/source/_themes/sphinx_rtd_theme/static/fonts and https://github.com/LaurentRDC/scikit-ued/blob/master/external/cif2cell-1.2.10/PyCifRW-3.3.tar.gz , they should be handled by LFS.

**Comment by LaurentRDC** [comment]
I switched the large files to LFS, but then the CI stopped working. I've decided against this complication. I might try this down the road, but right now it isn't worth the trouble.

**Comment by KOLANICH** [comment]
Thank you for the clarification.

>switched the large files to LFS

LFS is not for large files, it is for any binary files which are threated by git inefficiently.

**Comment by KOLANICH** [comment]
> -*.md filter=lfs diff=lfs merge=lfs -text
>-*.sh filter=lfs diff=lfs merge=lfs -text
>-*.rst filter=lfs diff=lfs merge=lfs -text

You are doing it wrong. LFS is only for binary (non-text) files. Text files are handled by git well.
