### ISSUE TITLE
silent relicensing to a viral license is not good

### ISSUE THREAD

**Issue by KOLANICH** [LaurentRDC/scikit-ued#34]
Since it will cause dependent packages to use the GPL v3-licensed package and to get infected.

IMHO: you should change package name, leaving scikit-ued MIT licensed, but unupdated, and use some other name for GPL-licensed successor, to prevent it from being automatically installed and used by non-GPL packages depending on scikit-ued.

**Comment by LaurentRDC** [comment]
The relicensing was not silent, as it has been announced in the changelog.

As far as I know, the only package that depends on scikit-ued is another package of mine, iris-ued. It is also being relicensed to GPLv3.

**Comment by KOLANICH** [comment]
>The relicensing was not silent, as it has been announced in the changelog.

Almost noone reads changelogs. People just declare scikit-ued as a dependency, and pip just installs the latest version. This way relicensing  without taking measures to prevent confusion  of GPLed version s to MITed ones automatically causes massive GPL violations. A paranoid psycho expecting such a relicense can even pin a version using `<` condition, it won't help: as long as he installed some GPLed software using GPLed version, `pip` will just upgrade it, and GPL will still be violated.

>As far as I know, the only package that depends on scikit-ued is another package of mine, iris-ued. It is also being relicensed to GPLv3.

We cannot know all the packages depending on scikit-ued, or any other library.
