### ISSUE TITLE
where are the tutorials data sets?

### ISSUE THREAD

**Issue by davidsaroff** [LaurentRDC/scikit-ued#35]
beginner trying to run a tutorial at 

https://scikit-ued.readthedocs.io/en/master/tutorials/baseline.html

a data set is loaded with the command
s, intensity = np.load("docs/tutorials/data/powder.npy")

I get an error
FileNotFoundError: [Errno 2] No such file or directory: 'docs/tutorials/data/powder.npy'

How do I download 'docs/tutorials/data/powder.npy'?
Or perhaps I already have but don't know the path.

I installed with anaconda3 on Windows 10 like this
(datashader) C:\Users\david>conda config --add channels conda-forge
(datashader) C:\Users\david>conda install scikit-ued

I copy and paste the example into a jupyter notebook, erasing the >>>'s

**Comment by LaurentRDC** [comment]
Hi David,

The data files are specified from the root of the git repository. 

If you install the package from conda, as you did, you don't get the tutorial data. To download it using git:

```bash
git clone https://github.com/LaurentRDC/scikit-ued
```

This will create a `scikit-ued` directory which looks just like the filestructure on the [home page](https://github.com/LaurentRDC/scikit-ued). From the root of this `scikit-ued` folder, the tutorial data is located at `docs/tutorials/data/...`

Let me know if this is clear

**Comment by davidsaroff** [comment]
Laurent,

Yes, thanks, that worked.

I look for pulsar signals in radio telescope data from the Green Bank Radio
Telescope. The raw signal is sliding window FFT'ed, technically polyphase
filter bank processed in a FPGA in real time. I get 4096 channels in the
range 300 - 400 MHz, a spectrum every 82 microseconds. My 40 hours of
telescope time is about 7 Tbytes.

The radio band used is military, so many channels are occupied, but a list
of them is not available. This becomes a baseline and peak finding problem,
to identify the channels to blank out, and what value to overwrite them.

All radio telescopes suffer from impulse noise from lightning worldwide.
Removing the lightning RF from the data also is a baseline and peak finding
problem.

After the military transmissions and lightning interference are
overwritten, I search for pulsar signals. Again baseline and peak finding
are the core of the work.

Your methods look quite promising for this!

David Saroff

**Comment by LaurentRDC** [comment]
That's quite an interesting use-case you have! I'm happy this might be useful beyond my work in condensed matter physics.

I'm closing this for now, but don't hesitate to open other issues if you need more support.
