### ISSUE TITLE
Mention baseline_dt() supports 2D data in the DOC

### ISSUE THREAD

**Issue by zxdawn** [LaurentRDC/scikit-ued#37]
#### Version / Platform Info
- scikit-ued Version: 2.1.7
- Happens in latest version? (Yes/No): Yes
- Known Operating System(s) affected__:
  - [x] Windows
  - [x] Linux
  - [x] Mac OS

#### Expected Behavior

In the [DOC](https://scikit-ued.readthedocs.io/en/master/tutorials/baseline.html):
> The [baseline_dt()](https://scikit-ued.readthedocs.io/en/master/functions/skued.baseline_dt.html#skued.baseline_dt) routine will usually be more accurate than its [baseline_dwt()](https://scikit-ued.readthedocs.io/en/master/functions/skued.baseline_dwt.html#skued.baseline_dwt) counterpart. However, [baseline_dwt()](https://scikit-ued.readthedocs.io/en/master/functions/skued.baseline_dwt.html#skued.baseline_dwt) can be applied to 1D and 2D data.

But, `baseline_dt()` also works for 2D data:

```
import numpy as np
from scipy import signal
from skued import baseline_dt

# create example data
t = np.linspace(-1, 1, 200, endpoint=False)
sig  = np.cos(2 * np.pi * 7 * t) + signal.gausspulse(t - 0.4, fc=2)
widths = np.arange(1, 31)
cwtmatr = signal.cwt(sig, signal.ricker, widths)

# get the baseline
baseline = baseline_dt(cwtmatr, wavelet = 'qshift3', level = 6, max_iter = 150)

# plot
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(6, 3))

ax1.imshow(cwtmatr)
ax2.imshow(baseline)
ax3.imshow(cwtmatr-baseline)

plt.tight_layout()
```

<img width="432" alt="output" src="https://user-images.githubusercontent.com/30388627/153597404-fb1709dc-9799-4b3d-9cb5-e9e2f76a872c.png">

So, is it better to say both support 1D and 2D data?

**Comment by LaurentRDC** [comment]
Ah yes you are right! The function documentation for `baseline_dt` mentions that it works for 1D and 2D. I will update the tutorial.

Thanks!

**Comment by zxdawn** [comment]
Thanks. It saves my life! Please see [my question](https://stackoverflow.com/a/71105067/7347925) on StackOverflow. (although it's downvoted ...)
