### ISSUE TITLE
Crystal orientation in kinematical single-crystal simulation

### ISSUE THREAD

**Issue by LittleLyon** [LaurentRDC/scikit-ued#39]
Hello,
I found scikit-ued very useful!

I would like to perform kinematical single-crystal simulation orienting the crystal to a different zone axis.
Could you improve the tutorial section with this case?  
https://scikit-ued.readthedocs.io/en/master/tutorials/simulation.html

Best regards
Luca

**Comment by LaurentRDC** [comment]
I don't have much free time these days. I can tell you how to do it though.

To perform the simulation with a different zone axis, you must create a `Crystal` object (from the `crystals` library) which has it's z-axis pointed in a different direction. For example, the graphite crystal:

```python
from crystals import Crystal
graphite = Crystal.from_database('C')
```
has its c-axis pointed in the z-direction. If you wanted the 100 zone axis, you would need to create a `Crystal` with the same atoms, but with the lattice arranged in a different way. You can read the [`crystals` documentation](https://crystals.readthedocs.io/en/master/) to learn how to do this.

**Comment by VRPHans** [comment]
I was playing around with the repo and came across the same issue. 
I ended up creating a new crystal with shuffled lattice vectors:

lat_vec = crystal.lattice_vectors

new_positions = [1, 0, 2]
lat_vec_shuff = tuple(lat_vec[i] for i in new_positions)
crys_shuffle = Crystal(crystal.atoms, lat_vec_shuff)
