### ISSUE TITLE
autocenter() fails with some SAED pattern

### ISSUE THREAD

**Issue by LittleLyon** [LaurentRDC/scikit-ued#40]
#### Version / Platform Info
- scikit-ued Version:  2.1.7
- Happens in latest version? (Yes/No):  yes
- Known Operating System(s) affected__:
  - [ x] Windows
  - [ ] Linux
  - [ ] Mac OS

#### Expected Behavior

autocenter() should find the pattern center

#### Actual Behavior

It results a wrong pattern center

#### Minimal Example of Issue

from skued import diffread, autocenter
import numpy as np
import matplotlib.pyplot as plt
from skimage.draw import polygon2mask

im = diffread('SAED_pattern.dm3')

fig, ax1 = plt.subplots(figsize = (4.5, 4.5))
ax1.imshow(im, cmap='gray', vmin=0, vmax=1000)

########## mask the beam stopper ########
polygon=np.array([[ 821.06421356, 1232.58513709],
                  [1128.41197691, 1368.52741703],
                  [1737.1969697 ,    9.1046176 ],
                  [1347.1017316 ,    9.1046176 ]])
mask = polygon2mask(im.shape, polygon) #create mask
mask=np.logical_not(mask) #invert mask

####################### find the pattern center ##############
rc, cc = autocenter(im, mask=mask)
[autocenter test.zip](https://github.com/LaurentRDC/scikit-ued/files/8142430/autocenter.test.zip)

ax1.scatter(cc, rc, color='r')

ax1.get_xaxis().set_visible(False)
ax1.get_yaxis().set_visible(False)
plt.tight_layout()
plt.show()

**Comment by LittleLyon** [comment]
[autocenter test.zip](https://github.com/LaurentRDC/scikit-ued/files/8142438/autocenter.test.zip)

**Comment by LittleLyon** [comment]
[autocenter test.zip](https://github.com/LaurentRDC/scikit-ued/files/8142449/autocenter.test.zip)

Sorry consider this attached files.

**Comment by LaurentRDC** [comment]
Hi there,

My only guess is that your diffraction pattern is not symmetric enough for the algorithm to work. For example, you have multiple equivalent reflections which differ significantly in intensity.

Can you 'normalize' this intensity to be more symmetric?

You can read the original source (Liu, Lai Chung. Chemistry in Action: Making Molecular Movies with Ultrafast Electron Diffraction and Data Science, Chapter 2. Springer Nature, 2020.) and try to improve on it for your case. If you find something that helps, it would be great if you could tell me so I can improve `autocenter`.
