### ISSUE TITLE
powdersim reciprocal lattice vector normalization issue

### ISSUE THREAD

**Issue by grahamsno** [LaurentRDC/scikit-ued#44]
#### Version / Platform Info
- scikit-ued Version: 2.1.13
- Happens in latest version? (Yes/No): Yes
- Known Operating System(s) affected:
  - [x] Windows
  - [ ] Linux
  - [ ] Mac OS

#### Expected Behavior

The unit of the reciprocal lattice vector that is used in the function ` powdersim` is expected to be 1/Å. (see [the documentation](https://scikit-ued.readthedocs.io/en/master/tutorials/simulation.html)).

#### Actual Behavior

The unit of $q$ in fact is $2\pi$/Å.

#### Minimal Example of Issue

I illustrated this issue in a [jupyter notebook](https://github.com/grahamsno/diffraction_simulation/blob/main/skued_powdersim.ipynb), where the result of scikit-ued is compared with the output of py4DSTEM.

**Comment by LaurentRDC** [comment]
You are right. The units of q can be inferred from the units of `crystals.Lattice.reciprocal_vectors` definition: https://github.com/LaurentRDC/crystals/blob/master/crystals/lattice.py#L145

I will update the documentation shortly.

**Comment by LaurentRDC** [comment]
The correct units are now reported, and version 2.1.14 will contain the corrected documentation.

Thanks for catching this bug!
